services:
  backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    restart: unless-stopped
    ports:
    - 5004:5004
    networks:
    - app-network
    environment:
      PORT: ${PORT}
      NODE_ENV: ${NODE_ENV}
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
    - 8085:80
    networks:
    - app-network
    environment:
      VITE_API_URL: ${VITE_API_URL}
    depends_on:
      backend:
        condition: service_started
networks:
  app-network:
    driver: bridge